### ISSUE TITLE
Q3: Shouldn't use multi-line ternary in solution.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-functions-ins-and-outs-assessment#103]
``` js
for (let i = 0; i < length; i++) {
    array[i] = typeof defaultValue === 'function' ?
      defaultValue(i) : defaultValue;
}
```

Suggestion:

``` js
for (let i = 0; i < length; i++) {
   if(typeof defaultValue === 'function'){
      array[i] = defaultValue(i)
   else{
      array[i] = defaultValue;
   }
}
```

**Comment by gaand** [comment]
If your formatting met our linter standards, I might have been persuaded. :-). 

I'd like to have a pedagogical chat about this.

**Comment by gaand** [comment]
It's only multiline because the variable names are so long, e.g.:

``` js
for (let i = 0; i < length; i++) {
    array[i] = defVal instanceof Function ? defVal(i) : defVal;
}
```

How do you feel about:

``` js
const newArray = function newArray(length, defVal) {
  let defValFunc = defVal instanceof Function ? defVal : () => defVal;
  let array = new Array(length);
  for (let i = 0; i < length; i++) {
    array[i] = defValFunc(i);
  }

  return array;
};
```

I think it's okay for solutions to be more than the developers can be expected to produce.  Perhaps we should warn them of that, but there's understanding to be gained in seeing more sophisticated code.  And unless I'm missing something, the linter does not object to multiline ternarys in JavaScript.And the linter is our judge of style (we may decide to change that, but it's not an issue now).

**Comment by payne-chris-r** [comment]
So, to be honest, ternaries always take me a 2nd or 3rd look to read cause I don't use them often (my problem, not OUR problem). I just thought that was a js "rule of thumb" or best practice to keep ?:s to a one line statement. I'm sure as shit not going to come in and tell you how to code. Just thought if I was a student trying to learn by taking a look at solution I might be like "HUH?" The strict adherence to the linter is also different than it was for me in 08 so I'm ok with your reasoning, just thought I'd give my 2 cents!

**Comment by gaand** [comment]
@payne-chris-r I understand.  Be glad you've never seen a ternary expression used as an l-value ;-).

What do you think of the options I presented?  Shortening names and/or refactoring code?

I'm quite interested in you 2-cents.

**Comment by jrhorn424** [comment]
I've been giving developers the advice that they should break ternaries into regular if-statements if their expressions exceed 80 characters.

It's a habit I picked up from Ruby.

**Comment by payne-chris-r** [comment]
And I learned it from Jeff. ;-)
I think I just hate ternaries. It's probably more MY issue than anything else. I can read it, it just doesn't feel easy to read to me. Most of that is just lack of practice with ternaries, but I think they make for code that's prickly to read. If they span multiple lines that prickliness increases IMHO. Don't get me wrong, your code is DEFINITELY sleeker (and actually pretty damn cool), but for someone like me who doesnt use ternaries, it's difficult to read.

**Comment by gaand** [comment]
I think there's pedagogical value to a solution using a ternary operator. Puzzling over such a thing will come up for the developers.
So the question is, which one?
I'll pick one of no one else has a strong opinion. I'll keep it to < 80 characters.

**Comment by BenGitsCode** [comment]
@J-Weeks @gaand @payne-chris-r  what's the consensus on this?

**Comment by gaand** [comment]
@BenGitsCode I picked one that is in `015/solution`.

I'm waiting for you to update solution from that before closing.

**Comment by gaand** [comment]
Closing based on 183098b6de8d480708acb34d2d2d607563d3860e
